development:
  adapter: postgresql
  database: blog_dev
  username: alexeyivanov

test:
  adapter: postgresql
  database: blog_test
  username: alexeyivanov

staging:
  adapter: postgresql
  database: blog_staging
  username: alexeyivanov

production:
  adapter: postgresql
  database: blog_staging
  username: alexeyivanov